[package]
name = "git-daily-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "git-daily-v2"
path = "src/main.rs"

[dependencies]
anyhow = "1"
rayon = "1"
colored = "2"
indicatif = "0.17"

[dev-dependencies]
tempfile = "3"
